-- virtual warehouses: etl, query
USE ROLE SYSADMIN;

CREATE WAREHOUSE ETL
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'A computing resource for dbt to run ETL';

CREATE WAREHOUSE QUERY
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'A computing resource for dbt to run ETL';

-- databases and schemas
CREATE DATABASE IF NOT EXISTS HR;
CREATE SCHEMA IF NOT EXISTS HR.SOURCE;
CREATE SCHEMA IF NOT EXISTS HR.MODEL;
CREATE SCHEMA IF NOT EXISTS HR.EXPOSE;
CREATE SCHEMA IF NOT EXISTS HR.UTIL;

CREATE DATABASE IF NOT EXISTS PAYROLL;
CREATE SCHEMA IF NOT EXISTS PAYROLL.SOURCE;
CREATE SCHEMA IF NOT EXISTS PAYROLL.MODEL;
CREATE SCHEMA IF NOT EXISTS PAYROLL.EXPOSE;
CREATE SCHEMA IF NOT EXISTS PAYROLL.UTIL;

-- roles and users
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS DBT_RW;
CREATE USER IF NOT EXISTS dbt
    PASSWORD='ddbt'
    LOGIN_NAME='dbt'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='ETL'
    DEFAULT_ROLE='DBT_RW'
    DEFAULT_NAMESPACE='HR.SOURCE'
    COMMENT='A dbt user used for ETL';

CREATE ROLE IF NOT EXISTS HR_RW;
CREATE ROLE IF NOT EXISTS PAYROLL_R;
CREATE USER IF NOT EXISTS jane_the_hr
    PASSWORD='jane'
    LOGIN_NAME='jane_the_hr'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='QUERY'
    DEFAULT_ROLE='HR_RW'
    DEFAULT_NAMESPACE='HR.SOURCE'
    COMMENT='hr jane';
CREATE USER IF NOT EXISTS joe_the_payroll
    PASSWORD='joe'
    LOGIN_NAME='joe_the_payroll'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='QUERY'
    DEFAULT_ROLE='PAYROLL_R'
    DEFAULT_NAMESPACE='PAYTOLL.SOURCE'
    COMMENT='payroll joe';

USE ROLE SECURITYADMIN;

GRANT ROLE DBT_RW TO USER dbt;
GRANT ROLE HR_RW TO USER jane_the_hr;
GRANT ROLE PAYROLL_R TO USER jane_the_hr;
GRANT ROLE PAYROLL_R TO USER joe_the_payroll;

-- set up permissions
USE ROLE SECURITYADMIN;

-- dbt_rw account level
GRANT USAGE ON WAREHOUSE ETL TO ROLE DBT_RW;
GRANT USAGE ON WAREHOUSE QUERY TO ROLE DBT_RW;
GRANT ALL ON DATABASE HR TO ROLE DBT_RW;
GRANT ALL ON DATABASE PAYROLL TO ROLE DBT_RW;
-- dbt_rw schema level
GRANT ALL ON ALL SCHEMAS IN DATABASE HR TO ROLE DBT_RW;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HR TO ROLE DBT_RW;
GRANT ALL ON ALL SCHEMAS IN DATABASE PAYROLL TO ROLE DBT_RW;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE PAYROLL TO ROLE DBT_RW;
-- dbt_rw object level
GRANT ALL ON ALL TABLES IN SCHEMA HR.SOURCE TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA HR.SOURCE TO ROLE DBT_RW;
GRANT ALL ON ALL TABLES IN SCHEMA HR.MODEL TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA HR.MODEL TO ROLE DBT_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA HR.EXPOSE TO ROLE DBT_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA HR.EXPOSE TO ROLE DBT_RW;
GRANT ALL ON ALL TABLES IN SCHEMA PAYROLL.SOURCE TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA PAYROLL.SOURCE TO ROLE DBT_RW;
GRANT ALL ON ALL TABLES IN SCHEMA PAYROLL.MODEL TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA PAYROLL.MODEL TO ROLE DBT_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA PAYROLL.EXPOSE TO ROLE DBT_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA PAYROLL.EXPOSE TO ROLE DBT_RW;

-- hr_rw account level
GRANT USAGE ON WAREHOUSE ETL TO ROLE HR_RW;
GRANT USAGE ON WAREHOUSE QUERY TO ROLE HR_RW;
GRANT ALL ON DATABASE HR TO ROLE HR_RW;
-- hr_rw schema level
GRANT ALL ON ALL SCHEMAS IN DATABASE HR TO ROLE HR_RW;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE HR TO ROLE HR_RW;
-- hr_rw object level
GRANT ALL ON ALL TABLES IN SCHEMA HR.SOURCE TO ROLE HR_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA HR.SOURCE TO ROLE HR_RW;
GRANT ALL ON ALL TABLES IN SCHEMA HR.MODEL TO ROLE HR_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA HR.MODEL TO ROLE HR_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA HR.EXPOSE TO ROLE HR_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA HR.EXPOSE TO ROLE HR_RW;

-- payroll_r account level
GRANT USAGE ON WAREHOUSE QUERY TO ROLE PAYROLL_R;
GRANT USAGE ON DATABASE PAYROLL TO ROLE PAYROLL_R;
-- payroll_r schema level
GRANT USAGE ON ALL SCHEMAS IN DATABASE PAYROLL TO ROLE PAYROLL_R;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PAYROLL TO ROLE PAYROLL_R;
-- payroll_r object level
GRANT SELECT ON ALL TABLES IN SCHEMA PAYROLL.SOURCE TO ROLE PAYROLL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYROLL.SOURCE TO ROLE PAYROLL_R;
GRANT SELECT ON ALL TABLES IN SCHEMA PAYROLL.MODEL TO ROLE PAYROLL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYROLL.MODEL TO ROLE PAYROLL_R;
GRANT SELECT ON ALL VIEWS IN SCHEMA PAYROLL.EXPOSE TO ROLE PAYROLL_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PAYROLL.EXPOSE TO ROLE PAYROLL_R;
