# Configuration for airbyte/destination-postgres
# Documentation about this connector can be found at https://docs.airbyte.io/integrations/destinations/postgres
resource_name: "dw_octavia"
definition_type: destination
definition_id: 25c5221d-dce2-4163-ade9-739ef790f503
definition_image: airbyte/destination-postgres
definition_version: 0.3.21

# EDIT THE CONFIGURATION BELOW!
configuration:
  host: host.docker.internal
  port: 5432 # REQUIRED | integer | Port of the database. | Example: 5432
  schema: "public" # REQUIRED | string | The default schema tables are written to if the source does not specify a namespace. The usual value for this field is "public". | Example: public
  database: dw-0003
  password: postgres
  username: postgres
  tunnel_method:
    tunnel_method: "NO_TUNNEL"
