version: "3"
services: 
  api: 
    image: hello_world_api:1.0
    container_name: hello_world_api
    ports: 
      - 5000:5000
    environment:
      - API_KEY=api_key
      - CITY=your_city
  
  hello_world:
    image: hello_world:1.0
    depends_on: 
      - api 
    environment:
      - API_ENDPOINT=hello_world_api:5000
      - NAME=your_name
